### PR TITLE
feat: add option to charge price per piece

### PR DESCRIPTION
**Pull request by xcudder**
I know there is a reason to charge per outfit, as that is what we ultimately save it, but I figure some people may want to charge more closely to a per item price and I don't imagine adding the option will hurt anyone.

### CODE REVIEW

**Review by Gellipapa — APPROVED** [review]
Hi! @xcudder Thank you for implemented this feature. Looks cool and plus toggle in Config nice job.

**Comment by Gellipapa** [comment]
@TheFantomas What do you think?

**Comment by TheFantomas** [comment]
> @TheFantomas What do you think?

I'm not kidding, it looks good. It can be turned off and on, so it is possible to configure it. So I don't see a problem with accepting this.

**Comment by Gellipapa** [comment]
Okey, @xcudder Thank you i merged.

**Pull request merged**
